In [1]:
import numpy as np

In [2]:
a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

# 1D Arrays

In [4]:
#How to create a basic array
a = np.array([1, 2, 3])
a

array([1, 2, 3])

In [6]:
b = np.zeros(2)
b

array([0., 0.])

In [7]:
c = np.ones(2)
c

array([1., 1.])

In [9]:
# Create an empty array with 2 elements
d = np.empty(2) 
d

array([1., 1.])

In [10]:
# create an array with a range of elements
e = np.arange(4)
e

array([0, 1, 2, 3])

In [11]:
# with specific range of elements
f=np.arange(2,20)
f

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [12]:
# continue
g = np.arange(2,20,2)
g

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# linearly spaced arrays
h=np.linspace(0,10,num=5) # gives use 5 nums
h

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [14]:
# specifice data types in array
i = np.ones(5,dtype=np.int8)
i

array([1, 1, 1, 1, 1], dtype=int8)

In [15]:
j  = np.ones(5,dtype=np.float64)
j

array([1., 1., 1., 1., 1.])

# 2D Arrays


In [16]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [18]:
np.empty((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# 3-D array

In [21]:
# making and reshaping a 3D array
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])