In [1]:
import numpy as np

# example sample
https://numpy.org/doc/stable/user/absolute_beginners.html#

# Create an array using numpy


In [2]:
# 1-D Array
food = np.array(["Pakora","Samosa","Raita"])
food

array(['Pakora', 'Samosa', 'Raita'], dtype='<U6')

In [3]:
price=np.array([5,5,5])
price

array([5, 5, 5])

In [4]:
type(price)

numpy.ndarray

In [5]:
type(food)

numpy.ndarray

In [6]:
len(food)

3

In [7]:
price[2]

5

In [8]:
price[0:]

array([5, 5, 5])

In [9]:
food[1]

'Samosa'

In [10]:
price.mean()

5.0

In [11]:
# zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [12]:
# ones
np.ones(5)

array([1., 1., 1., 1., 1.])

In [13]:
# empty

np.empty(5)

# The function empty creates an array whose initial content is random and depends on the state of the memory.
# The reason to use empty over zeros (or something similar) is speed.

array([1., 1., 1., 1., 1.])

In [14]:
#range
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# specify
np.arange(2,20)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [16]:
# specific interval
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [20]:
# table 0f 5
np.arange(5,55,5)

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [22]:
# line space
np.linspace(0,100,num=5)

array([  0.,  25.,  50.,  75., 100.])

In [23]:
# specify your data type
np.ones(5,dtype=np.int64)

array([1, 1, 1, 1, 1], dtype=int64)

In [24]:
np.ones(5,dtype=np.float64)

array([1., 1., 1., 1., 1.])

# Array functions

In [26]:
a = np.array([10,12,15,2,4,6,100,320,0.5,10.3])
a

array([ 10. ,  12. ,  15. ,   2. ,   4. ,   6. , 100. , 320. ,   0.5,
        10.3])

In [28]:
a.sort()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [29]:
a.all()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [30]:
a.any()
a

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ])

In [32]:
b = np.array([10.2,3.4,53.6,91.6,45.5])
b

array([10.2,  3.4, 53.6, 91.6, 45.5])

In [34]:
c = np.concatenate((a,b))
c

array([  0.5,   2. ,   4. ,   6. ,  10. ,  10.3,  12. ,  15. , 100. ,
       320. ,  10.2,   3.4,  53.6,  91.6,  45.5])

In [35]:
c.sort()
c

array([  0.5,   2. ,   3.4,   4. ,   6. ,  10. ,  10.2,  10.3,  12. ,
        15. ,  45.5,  53.6,  91.6, 100. , 320. ])

# 2-D arrays

In [36]:
a= np.array([[1,2,3,4,5],[5,4,3,2,1]])
a

array([[1, 2, 3, 4, 5],
       [5, 4, 3, 2, 1]])

In [42]:

b = np.array([[6,7,8,9,10],[8,9,10,11,12]])
b


array([[ 6,  7,  8,  9, 10],
       [ 8,  9, 10, 11, 12]])

In [44]:
# contancate
c = np.concatenate((a,b),axis=1)
c

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 5,  4,  3,  2,  1,  8,  9, 10, 11, 12]])

In [46]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [49]:
# to din the number of dimenison
array_example.ndim

3

In [52]:
type(a)

numpy.ndarray

In [50]:
b=np.array([[5,6,7],
[8,9,10],
[10,11,12]])
b

array([[ 5,  6,  7],
       [ 8,  9, 10],
       [10, 11, 12]])

In [51]:
b.ndim

2

In [54]:
# size(number of elements)
array_example.size

24

In [55]:
# shape
array_example.shape

(3, 2, 4)

In [63]:
a = np.arange(9) # 3 * 3
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [64]:
# reshape
b = a.reshape(3,3) # 3 * 3
b

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [65]:
# reshape
np.reshape(a, newshape=(1, 9), order='C')

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [66]:
# convert 1d into 2d
a = np.array([1, 2, 3, 4, 5, 6])
a

array([1, 2, 3, 4, 5, 6])

In [67]:
a.shape

(6,)

In [69]:
# row wise
b = a[np.newaxis, :]
b

array([[1, 2, 3, 4, 5, 6]])

In [70]:
b.shape

(1, 6)

In [72]:
# column wise
c = a[ :,np.newaxis]
c

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [73]:
# slicing
a[2:6]


array([3, 4, 5, 6])

In [74]:
a*6

array([ 6, 12, 18, 24, 30, 36])

In [75]:
a+6

array([ 7,  8,  9, 10, 11, 12])

In [76]:
a.sum()

21

In [77]:
#a.mean()

3.5